PhoneResponsive={"785":{
"pageLayer":{"w":785,"h":450,"bgColor":"#f9cb9c"}
,
"image74496":{"x":0,"y":0,"w":785,"h":442,"bOffBottom":0,"i":"images/16.png"}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"480":{
"pageLayer":{"w":480,"h":763,"bgColor":"#f9cb9c"}
,
"image74496":{"x":0,"y":0,"w":480,"h":270,"bOffBottom":0,"i":"images/16.png"}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
