TabletResponsive={"1009":{
"pageLayer":{"w":1009,"h":662,"bgColor":"#f9cb9c"}
,
"image74503":{"x":0,"y":0,"w":1009,"h":568,"bOffBottom":0,"i":"images/17.png"}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"785":{
"pageLayer":{"w":785,"h":1000,"bgColor":"#f9cb9c"}
,
"image74503":{"x":0,"y":0,"w":785,"h":442,"bOffBottom":0,"i":"images/17.png"}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
