DesktopResponsive={"1009":{
"pageLayer":{"w":1600,"h":900,"bgColor":"#f9cb9c"}
,
"image74496":{"x":0,"y":0,"w":1600,"h":900,"bOffBottom":0,"i":"images/16.png"}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":['images/16.png']
}}
